name: quran_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  google_fonts: 2.3.1
  http: 0.13.4
  shimmer: ^2.0.0
  flutter_shimmer: 2.1.2
  audioplayers: 0.20.1
  convex_bottom_bar: 3.0.0
  intl: 0.17.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
    - assets/images/
    - assets/svg/
  uses-material-design: true

